### ISSUE TITLE
请问还有在更新吗，求最新EFI

### ISSUE THREAD

**Issue by zhouxiangfeng** [istarmeow/Dell.ChengMing.3991-OpenCore.0.6.4-macOS.Big.Sur.11.1#1]

**Comment by istarmeow** [comment]
有更新了

**Comment by zhouxiangfeng** [comment]
感谢大佬

**Comment by zhouxiangfeng** [comment]
大佬，用了你的最新的EFI好像键盘鼠标驱动不了，是不是配置的问题，用您以前的EFI能驱动

**Comment by istarmeow** [comment]
USB相关配置未做更新，但OpenCore版本号更新了，不确定是否有影响，我这台测试无异常


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "istarmeow/Hackintosh-Dell.ChengMing.3991-OpenCore.0.7.0-macOS.Big.Sur.11.4"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 晚上8:05
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [istarmeow/Hackintosh-Dell.ChengMing.3991-OpenCore.0.7.0-macOS.Big.Sur.11.4] 请问还有在更新吗，求最新EFI (#1)





 
大佬，用了你的最新的EFI好像键盘鼠标驱动不了，是不是配置的问题，用您以前的EFI能驱动

**Comment by zhouxiangfeng** [comment]
明白，是我鼠标键盘插错孔了，声音输出没有问题了，声音输入是不是可以通过改alcid实现

**Comment by istarmeow** [comment]
声音输入目前还不知怎么解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "istarmeow/Hackintosh-Dell.ChengMing.3991-OpenCore.0.7.0-macOS.Big.Sur.11.4"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 晚上8:11
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [istarmeow/Hackintosh-Dell.ChengMing.3991-OpenCore.0.7.0-macOS.Big.Sur.11.4] 请问还有在更新吗，求最新EFI (#1)





 
明白，是我鼠标键盘插错孔了，声音输出没有问题了，声音输入是不是可以通过改alcid实现

**Comment by zhouxiangfeng** [comment]
这里有解决声音输入的方法，我试了可以https://blog.csdn.net/weixin_41125409/article/details/96768880

**Comment by istarmeow** [comment]
方案二测试过，似乎还是无效




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "istarmeow/Hackintosh-Dell.ChengMing.3991-OpenCore.0.7.0-macOS.Big.Sur.11.4"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 晚上7:56
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [istarmeow/Hackintosh-Dell.ChengMing.3991-OpenCore.0.7.0-macOS.Big.Sur.11.4] 请问还有在更新吗，求最新EFI (#1)





 
这里有解决声音输入的方法，我试了可以https://blog.csdn.net/weixin_41125409/article/details/96768880

**Comment by zhouxiangfeng** [comment]
要先替换驱动VerbStub.kext  去这里下最新的驱动https://github.com/hackintosh-stuff/ComboJack，然后按照上面那个教程操作

**Comment by istarmeow** [comment]
可以了，使用的前置耳麦口，同时也解决了Dell7080的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "istarmeow/Hackintosh-Dell.ChengMing.3991-OpenCore.0.7.0-macOS.Big.Sur.11.4"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 晚上8:34
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [istarmeow/Hackintosh-Dell.ChengMing.3991-OpenCore.0.7.0-macOS.Big.Sur.11.4] 请问还有在更新吗，求最新EFI (#1)





 
要先替换驱动VerbStub.kext  去这里下最新的驱动https://github.com/hackintosh-stuff/ComboJack ，然后按照上面那个教程操作

**Comment by zhouxiangfeng** [comment]
请问一下怎么驱动USB3.0呢，用您的最新efi我的驱动不了

**Comment by istarmeow** [comment]
参考 https://heipg.cn/tutorial/customize-usb-port-windows.html 完成该机型定制，建议winpe下使用，挺方便的，我没做这个机型定制，测试在dell7080可行
