### ISSUE TITLE
试了几个镜像都不成功，能提供下镜像的下载地址吗？

### ISSUE THREAD

**Issue by 1371030** [istarmeow/Dell.ChengMing.3991-OpenCore.0.6.4-macOS.Big.Sur.11.1#2]
试了几个镜像都不成功，能提供下镜像的下载地址吗？

**Comment by istarmeow** [comment]
在黑苹果星球下载的------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月8日(星期六) 下午5:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[istarmeow/Hackintosh-Dell.ChengMing.3991-OpenCore.0.6.4-macOS.Big.Sur.11.1] 试了几个镜像都不成功，能提供下镜像的下载地址吗？ (#2)
