### ISSUE TITLE
紫屏问题

### ISSUE THREAD

**Issue by jinxiangqiang** [istarmeow/Dell.ChengMing.3991-OpenCore.0.6.4-macOS.Big.Sur.11.1#4]
你好，紫屏问题怎么修复的，我有一台也紫屏

**Comment by istarmeow** [comment]
可以参考下 [黑苹果Big Sur进入桌面紫屏问题](https://blog.starmeow.cn/detail/0f49c89d1e7298bb9930789c8ed59d48/)
